name: Build extension

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: npm install

    - name: Build for firefox
      run: npm run build:prod:firefox

    - name: Lint using web-ext
      run: npx web-ext lint --config=web-ext.firefox.js
      
    - name: Build dist for firefox
      run: npm run dist:firefox
      
    - name: Build source archive
      run: npm run dist:source
      
    - name: Create a release
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref }}
          GITHUB_USER: ${{ github.repository_owner }}
          GITHUB_REPO: ao3-enhancements
      run: |
        export VERSION="${TAG:1}"
        wget https://github.com/github-release/github-release/releases/download/v0.8.1/linux-amd64-github-release.bz2 -O github-release.bz2
        bzip2 -d github-release.bz2
        chmod +x github-release
        ./github-release release --draft --tag $TAG --name "Release $TAG" --description "Write description here"
        ./github-release upload --tag $TAG --name "ao3-enhancements-$VERSION.firefox.zip" --file dist/firefox/ao3-enhancements-$VERSION.zip
        ./github-release upload --tag $TAG --name "ao3-enhancements-$VERSION.source.zip" --file dist/ao3-enhancements-$VERSION.source.zip
